#!/usr/bin/env bash
# Bash script that displays lines containing the bash word
# ps --forest -eo user,pid,%cpu,%mem,vsz,rss,tname,stat,start_time,bsdtime,command | grep bash | tail -n +2
# shellcheck disable=SC2009
ps aux --forest | grep bash | tail -n +2
